import { readFileSync, writeFileSync } from "node:fs";

// Kept as a tooling asset (not deleted with the rest of src/fonts): it is the
// only source this script can read glyph path data from, so removing it would
// make adding a future icon require re-sourcing a Font Awesome 4 font.
const FONT = "scripts/fontawesome-webfont.svg";
const ASCENT = 1536;
const UPM = 1792;

const ICONS = {
  "arrow-left": "f060",
  "hand-o-up": "f0a6",
  "angle-left": "f104",
  "angle-right": "f105",
  "angle-up": "f106",
  "angle-down": "f107",
};

const src = readFileSync(FONT, "utf8");
const defaultAdv = Number(/<font[^>]*horiz-adv-x="(\d+)"/.exec(src)[1]);
const byCodepoint = new Map();

for (const match of src.matchAll(/<glyph([^>]*)\/>/g)) {
  const attrs = match[1];
  const unicode = /unicode="&#x([0-9a-fA-F]+);"/.exec(attrs);
  const d = /\sd="([^"]+)"/.exec(attrs);
  if (!unicode || !d) continue;
  const adv = /horiz-adv-x="(\d+)"/.exec(attrs);
  byCodepoint.set(unicode[1].toLowerCase(), {
    d: d[1],
    adv: adv ? Number(adv[1]) : defaultAdv,
  });
}

const entries = Object.entries(ICONS).map(([name, cp]) => {
  const glyph = byCodepoint.get(cp);
  if (!glyph) throw new Error(`glyph ${name} (U+${cp}) not found in ${FONT}`);
  return `  "${name}": {\n    viewBox: "0 0 ${glyph.adv} ${UPM}",\n` +
         `    d: "${glyph.d}",\n  },`;
});

const output = `// Generated by scripts/generate-icons.mjs from the Font Awesome 4 SVG font.
// Do not edit by hand.

const ICONS = {
${entries.join("\n")}
} as const;

export type IconName = keyof typeof ICONS;

type IconProps = {
  name: IconName;
  className?: string;
  onClick?: () => void;
};

const Icon = ({ name, className, onClick }: IconProps) => {
  const { viewBox, d } = ICONS[name];

  return (
    <svg
      className={className}
      onClick={onClick}
      viewBox={viewBox}
      width="1em"
      height="1em"
      fill="currentColor"
      aria-hidden="true"
      focusable="false"
    >
      <g transform="translate(0, ${ASCENT}) scale(1, -1)">
        <path d={d} />
      </g>
    </svg>
  );
};

export default Icon;
`;

writeFileSync("src/components/common/Icon.tsx", output);
console.log(`generated ${entries.length} icons`);
